import localFont from "next/font/local";
import "./globals.css";
import { Josefin_Sans } from "next/font/google";
import Footer from "@/app/footer/page";
import WhatsAppButton from "@/app/common/WhatsAppButton";
import ReduxProvider from "@/app/components/ReduxProvider";

const josefin = Josefin_Sans({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Maazster Edu",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
    apple: "/favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${josefin.className} antialiased bg-primary-950 text-primary-100 min-h-screen flex flex-col relative`}
      >
        <ReduxProvider>
          {children}
          <WhatsAppButton />
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
